<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2016 Marcel Djaman
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

$title = $this->translate('Evènements');
$events = $this->event;
?>

<section class="content-header">
    <h1>
        <?php echo $title; ?>
        <small><?php echo $this->translate('Timeline') ?></small>
    </h1>
    <p><a href="<?php echo $this->url('event', [], ['query' => [
            'agenda' => 1
        ]]) ?>"><i class="fa fa-calendar-check-o"></i> <?php echo $this->translate('Basculer vers agenda') ?></a></p>
</section>

<!-- Main content -->
<section class="content">
    <!-- row -->
    <div class="row">
        <div class="col-md-12">
            <!-- The time line -->
            <ul class="timeline">
                <!-- timeline time label -->
                <li class="time-label">
                  <span class="bg-red">10 Feb. 2014</span>
                </li>
                <!-- /.timeline-label -->
                <!-- timeline item -->
                <?php foreach ($events as $item) : ?>
                <?php /* @var \MdjamanEvent\Entity\Event $item */ ?>
                <li>
                    <i class="fa fa-envelope bg-blue"></i>
                    <div class="timeline-item">
                        <span class="time"><i class="fa fa-clock-o"></i> <?php echo $item->getStartDate()->format('H:i') ?></span>

                        <h3 class="timeline-header"><a href="#"><?php echo $item->getName() ?></a></h3>

                        <div class="timeline-body"><?php echo $item->getDetails() ?></div>
                        <div class="timeline-footer">
                            <a class="btn btn-primary btn-xs">Read more</a>
                            <a class="btn btn-danger btn-xs">Delete</a>
                        </div>
                    </div>
                </li>
                <!-- END timeline item -->
                <?php endforeach; ?>
            </ul>
        </div>
        <!-- /.col -->
    </div>
</section>
