<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2016 Marcel Djaman
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

namespace MdjamanEvent\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * @param array $criteria
     * @return string
     */
    public function countResult($criteria)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->select('COUNT(e.id)');

        $x = 1;
        foreach ($criteria as $key => $value) {
            if ($key !== '') {
                $qb->andWhere("e.$key = ?$x");
                $qb->setParameter($x, $value);
                ++$x;
            }
        }

        $query = $qb->getQuery();

        $cacheKey = md5(__FUNCTION__ . json_encode(func_get_args()));
        $query->useQueryCache(true)
            ->useResultCache(true, 3600, $cacheKey);

        return $query->getSingleScalarResult();
    }

    /**
     * List events
     *
     * @param boolean|null $active
     * @param string $orderBy
     * @param string $dir
     * @param int $limit max results to retrieve
     * @param int|null $offset
     * @param boolean $active only published or not
     * @return mixed
     */
    public function findEvents($active = true, $orderBy = 'startDate', $dir = 'desc', $limit = 20, $offset = null)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->addSelect(array('c'))
            ->leftJoin('a.type', 'c');

        if ($active === true) {
            $qb->where('a.active = 1');
        }

        $qb->orderBy('a.'. $orderBy, $dir);

        $query = $qb->getQuery();
        if (null !== $limit) {
            $query->setMaxResults($limit);
            if (null !== $offset) {
                $query->setFirstResult($offset);
            }
        }

        $cacheKey = md5(__FUNCTION__ . json_encode(func_get_args()));
        $query->useQueryCache(true);
        $query->useResultCache(true, 3600, $cacheKey);

        return $query->getResult();
    }

    /**
     * Find a event by it's id value
     *
     * @param int $id
     * @param boolean $active
     * @return mixed
     */
    public function findOneById($id, $active = true)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->leftJoin('n.type', 'c')
            ->where('n.id = ?1')
            ->setParameter(1, $id);

        if ($active == true) {
            $qb->andWhere('n.active = 1');
        }

        $query = $qb->getQuery();

        $cacheKey = __FUNCTION__ . json_encode(func_get_args());
        $query->useQueryCache(true);
        $query->useResultCache(true, 3600, $cacheKey);

        return $query->getResult();
    }

    /**
     * Find a event by it's alias value
     *
     * @param string $alias
     * @param boolean $active
     * @return mixed
     */
    public function findOneByAlias($alias, $active = true)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->addSelect(array('c', 't'))
            ->leftJoin('n.type', 'c')
            ->leftJoin('n.tags', 't')
            ->where('n.alias = ?1')
            ->setParameter(1, $alias);

        if ($active) {
            $qb->andWhere('n.active = 1');
        }

        $query = $qb->getQuery();

        $cacheKey = md5(__FUNCTION__ . json_encode(func_get_args()));
        $query->useQueryCache(true);
        $query->useResultCache(true, 3600, $cacheKey);

        return $query->getOneOrNullResult();
    }

    /**
     *
     * Paginate event of a type
     * @param int $type
     * @param boolean $active if true only active will be fetch
     * @param string $orderBy if true only active will be fetch
     * @param string $dir
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function queryEventByType($type, $active = true, $orderBy = 'created_at', $dir = 'desc')
    {
        $qb = $this->createQueryBuilder('n');
        $qb->where('n.type = ?1')
            ->setParameter(1, $type);

        if ($active == true) {
            $qb->andWhere('n.active = 1');
        }

        $qb->orderBy('n.' . $orderBy, $dir);

        return $qb;
    }

    /**
     *
     * Paginate event of a type
     * @param array $tags
     * @param boolean $active if true only active will be fetch
     * @param string $orderBy
     * @param string $dir
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function queryEventByTags($tags, $active = true, $orderBy = 'created_at', $dir = 'desc')
    {
        $qb = $this->createQueryBuilder('n');
        $qb->addSelect(array('c', 't'))
            ->leftJoin('n.type', 'c')
            ->leftJoin('n.tags', 't');
        $qb->where('t.id IN (:ids)')
            ->setParameter('ids', $tags);

        if ($active == true) {
            $qb->andWhere('n.active = 1');
        }

        $qb->orderBy('n.' . $orderBy, $dir);

        return $qb;
    }

    /**
     *
     * Paginate event of a type
     * @param int $type
     * @param boolean $active if true only active will be fetch
     * @param string $orderBy the sorted column
     * @param string $dir sorting direction
     * @return \Doctrine\ORM\Query
     */
    public function paginateByType($type, $active = true, $orderBy = 'created_at', $dir = 'desc')
    {
        $qb = $this->queryEventByType($type, $active, $orderBy, $dir);

        $query = $qb->getQuery();

        $cacheKey = __FUNCTION__ . json_encode(func_get_args());
        $query->useQueryCache(true);
        $query->useResultCache(true, 3600, $cacheKey);

        return $query;
    }

    /**
     *
     * Paginate event by a tag
     * @param string $tag
     * @param boolean $active if true only active will be fetch
     * @return void
     */
    public function paginateByTag($tag, $active = true)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->where($qb->expr()->like('n.tag', '?1'));

        if ($active == true) {
            $qb->andWhere('n.active = 1');
        }

        $query = $qb->getQuery();
        $query->setParameter(1, '%' . $tag . '%');

        $cacheKey = __FUNCTION__ . json_encode(func_get_args());
        $query->useQueryCache(true);
        $query->useResultCache(true, 3600, $cacheKey);

        return $query;
    }

    /**
     * Event published by a user
     *
     * @param int $user id of user
     * @param boolean $active
     * @param int $limit
     * @param int $offset
     * @return mixed
     */
    public function findAllByUser($user, $active = true, $limit = 20, $offset = null)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->where('n.user = ?1')
            ->setParameter(1, $user);

        if ($active) {
            $qb->andWhere('n.active = 1');
        }

        $qb->orderBy('n.publishDate', 'DESC');

        $query = $qb->getQuery();
        if (null !== $limit) {
            $query->setMaxResults($limit);
            if (null !== $offset) {
                $query->setFirstResult($offset);
            }
        }

        $cacheKey = __FUNCTION__ . json_encode(func_get_args());
        $query->useQueryCache(true);
        $query->useResultCache(true, 3600, $cacheKey);

        return $query->getResult();
    }

    /**
     *
     * Paginate event by a user
     * @param int $user id of user
     * @param boolean $publish
     * @return void
     */
    public function paginateAllByUser($user, $publish = 1)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->where('n.user = ?1')
            ->setParameter(1, $user);

        if ($publish == 0) {
            $qb->andWhere('n.active = 0');
        }

        $qb->orderBy('n.publishDate', 'DESC');

        $query = $qb->getQuery();

        $query->useQueryCache(true);
        $query->useResultCache(true, 3600, $user.$publish);

        return $query;
    }

    /**
     * Find events of a type id
     *
     * @param mixed $type
     * @param boolean $active
     * @param null|string $exclude
     * @param string $orderBy
     * @param string $dir
     * @param null|int $limit
     * @param null|int $offset
     * @return mixed
     */
    public function findEventByType($type, $active = true, $exclude = null, $orderBy = 'created_at', $dir = 'desc', $limit = 20, $offset = null)
    {
        $qb = $this->queryEventByType($type, $active, $orderBy, $dir);
        if (null !== $exclude) {
            $qb->andWhere('n.id != :exclude');
            $qb->setParameter('exclude', $exclude);
        }

        $query = $qb->getQuery();

        if (null !== $limit) {
            $query->setMaxResults($limit);
            if (null !== $offset) {
                $query->setFirstResult($offset);
            }
        }

        $cacheKey = __FUNCTION__ . json_encode(func_get_args());
        $query->useQueryCache(true);
        $query->useResultCache(true, 3600, $cacheKey);

        return $query->getResult();
    }

    /**
     * @param array|mixed $tags
     * @param bool $active
     * @param string $orderBy
     * @param string $dir
     * @param int $limit
     * @param null $offset
     * @return array
     */
    public function findEventByTags($tags, $active = true, $orderBy = 'created_at', $dir = 'desc', $limit = 20, $offset = null)
    {
        $tags = (array) $tags;
        $qb = $this->queryEventByTags($tags, $active, $orderBy, $dir);

        $query = $qb->getQuery();

        if (null !== $limit) {
            $query->setMaxResults($limit);
            if (null !== $offset) {
                $query->setFirstResult($offset);
            }
        }

        $cacheKey = md5(__FUNCTION__ . json_encode(func_get_args()));
        $query->useQueryCache(true);
        $query->useResultCache(true, 3600, $cacheKey);

        return $query->getResult();
    }

}
